name: Deploy preview to Vercel

# on:
#   pull_request:
#     branches:
#       - main
#       - dev
#     types:
#       - opened
#       - synchronize
#       - reopened
#
jobs:
  deploy:
    name: Deploy
    if: ${{ github.repository == 'capytalcode/project-extrovert' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Build
        run: |
          make build/static
      - name: Deploy
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_DEPLOYMENT: false
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ SECRETS.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ SECRETS.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: false
